// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMt5n2db0lG2lwcOBEEDRf98HXm1CC3L8',
    appId: '1:632437494938:web:1156495bb54b3eb3e6bb23',
    messagingSenderId: '632437494938',
    projectId: 'sales-manager-1d0dc',
    authDomain: 'sales-manager-1d0dc.firebaseapp.com',
    storageBucket: 'sales-manager-1d0dc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOLH3mHTq5JLrZsdABboEbjQLMh4PuWYI',
    appId: '1:632437494938:android:3f9924fefd45125de6bb23',
    messagingSenderId: '632437494938',
    projectId: 'sales-manager-1d0dc',
    storageBucket: 'sales-manager-1d0dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1K6V6CoVfqn-7wEnIDchE4ClTYt-SnJc',
    appId: '1:632437494938:ios:393372efb9c6946ee6bb23',
    messagingSenderId: '632437494938',
    projectId: 'sales-manager-1d0dc',
    storageBucket: 'sales-manager-1d0dc.appspot.com',
    iosClientId: '632437494938-f7qg71019hhma55c2am5kadqau0ihvvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1K6V6CoVfqn-7wEnIDchE4ClTYt-SnJc',
    appId: '1:632437494938:ios:393372efb9c6946ee6bb23',
    messagingSenderId: '632437494938',
    projectId: 'sales-manager-1d0dc',
    storageBucket: 'sales-manager-1d0dc.appspot.com',
    iosClientId: '632437494938-f7qg71019hhma55c2am5kadqau0ihvvi.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesManager',
  );
}
